### ISSUE TITLE
Sometimes, the status dashboard does'nt reflect the true statuses

### ISSUE THREAD

**Issue by danypoup** [statusdashboard/statusdashboard#19]
Sometimes, I can see differences between dahsboard and logs from server.js.

Some services are displayed with a DOWN or UNKNOWN  status while server says they are all UP. And they are really UP !! 

Moreover, It's a random problem. 

Config: 
LinuxMint 9 Isadora x86_64 - Kernel 2.6.32
Node.js 0.6.7
Statusdashboard rev fc51700

**Comment by obazoud** [comment]
There may be a bug in 'command' implementation, pull request are welcome.

**Comment by stelcheck** [comment]
Unknown happens because sometimes the server sends statuses before all results for commands results are actually in. Normally, you can fix this by increasing the serviceDelay configuration (and make sure serviceDelay is shorter than serviceInterval)

**Comment by obazoud** [comment]
Could you use the lastest version ?
Feel free to re open this issue if it happens again.
