### ISSUE TITLE
no devices shown

### ISSUE THREAD

**Issue by samports** [statusdashboard/statusdashboard#22]
when i launch node server.js i am able to access the webserver but it is not showing any checks that are in settings.js it just says 0 up 0 critical 0 down.

**Comment by obazoud** [comment]
Hi @samports,
yes by default, there is no check configuration. Maybe I can improve it for a better first impression.
You need to configure yours settings to see something.
If you have already settings, can you send me your configuration to have a look at your problem.

Olivier.

**Comment by samports** [comment]
i think i figured it out, after adding the export app_env="olivier" i can atleast now see your default checks :) thanks
