### ISSUE TITLE
SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol error

### ISSUE THREAD

**Issue by ghost** [statusdashboard/statusdashboard#31]
I am using statusdashboard to check status of my website using https and it is showing following error on the dashboard.

"SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:."

I am fairly new in using Node.js, can you please guide me how to connect to servers that use HTTPS protocol.

Edit:

Works absolutely fine with 'http.'

**Comment by warmfusion** [comment]
Can you copy and paste the section of the settings around the http/https path.

What happens if you try the following command

openssl s_client -connect yourserver.com:443

**Comment by ghost** [comment]
settings['xyz'] = {
    port: 8080,
    hostname: '0.0.0.0',
    services: [{
      name: 'qa', 
      label: 'QA',
      check: 'https',
      host: '192.xx.xx.xx', 
      port: '80',
      path: '/'
    }, {
      name: 'qa2', 
      label: 'QA 2',
      check: 'https',
      host: '192.xy.xy.xx', 
      port: '80',
      path: '/'
    },

And using that command returns the server certificate and a couple of other parameters.

Also: I used http instead of https and it worked fine, but I am just curious now what is happening with https.

**Comment by warmfusion** [comment]
Ok, here's the issue;

Http traffic and https traffic use different ports. Typical http uses port 80, as you have specified, but https traffic typically uses port 443. The open_Ssl command shows this as it specifically mentions port 443, but most users never see port 80/443 in their browsers as they're hidden ( unless set to non standard values.)

When using https, set the port to 443.

Try opening your http site using https://192.x.x.x:80/ in your normal browser and it will complain in a similar fashion to the statusboard.

Hope this helps.

**Comment by ghost** [comment]
Hmmm I see, thanks for the explanation. 

Also I tried using port 443 with HTTPS and it returns "unknown" status on the dashboard, tried it with couple of other https services too and the same result.

**Comment by obazoud** [comment]
Feel free to re-open if you have question.

**Comment by yryz** [comment]
# SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

var https = require('https');

https.get('https://test-api.geotrust.com/webtrust/query.jws?WSDL', function(res) {
  console.log("statusCode: ", res.statusCode);
  console.log("headers: ", res.headers);

  res.on('data', function(d) {
    process.stdout.write(d);
  });

}).on('error', function(e) {
  console.error(e);
});

**Comment by obazoud** [comment]
Hi,

Try this:

``` javascript
var https = require('https');

https.globalAgent.options.secureProtocol = 'SSLv3_method';

var options = {
  hostname: 'test-api.geotrust.com',
  port: 443,
  path: '/webtrust/query.jws?WSDL',
  method: 'GET'
};

var req = https.request(options, function(res) {
  console.log("statusCode: ", res.statusCode);
  console.log("headers: ", res.headers);

  res.on('data', function(d) {
    process.stdout.write(d);
  });
});
req.end();

req.on('error', function(e) {
  console.error(e);
});
```

And I got the WSDL.

``` shell
 % node index.js
statusCode:  200
headers:  { date: 'Tue, 14 Jan 2014 19:37:42 GMT',
  'transfer-encoding': 'chunked',
  'content-type': 'text/xml; charset=UTF-8' }
<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="queryDefinitions" targetNamespace="http://api.geotrust.com/webtrust/query" xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://api.geotrust.com/webtrust/query" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s3="http://www.openuri.org/2006/12/wsdl/upgradedJWS">
  <s0:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://api.geotrust.com/webtrust/query" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://api.geotrust.com/webtrust/query" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s3="http://www.openuri.org/2006/12/wsdl/upgradedJWS" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="GetQuickApproverListInput">
        <xs:sequence>
...
```

**Comment by obazoud** [comment]
No more feedbacks, closing issue.
Feel free to re-open if you have questions.
