### ISSUE TITLE
Dynamically adding/removing services

### ISSUE THREAD

**Issue by stelcheck** [statusdashboard/statusdashboard#35]
Hi,

How would I go about if I wanted to add/remove dynamically new services? As in, adding/removing checks dynamically from within the code?

**Comment by chamerling** [comment]
Hi @stelcheck 

This is not implemented. For now, all is defined by configuration. Will be a nice pull-request ;)

**Comment by stelcheck** [comment]
OK, ill see what I can do.

Where should I look in the code? I have a hard time to see where the tests
gets executed.

Kind regards,

On Tue, Jan 15, 2013 at 5:40 PM, Christophe Hamerling <
notifications@github.com> wrote:

> Hi @stelcheck https://github.com/stelcheck
> 
> This is not implemented. For now, all is defined by configuration. Will be
> a nice pull-request ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/obazoud/statusdashboard/issues/35#issuecomment-12257919.

## 

http://www.wizcorp.jp/Marc Trudel-Belisle

## Chief Technology Officer | Wizcorp Inc. http://www.wizcorp.jp/

TECH . GAMING . OPEN-SOURCE WIZARDS+ 81
3-4550-1448|Websitehttp://www.wizcorp.jp/
|Twitter https://twitter.com/Wizcorp|Facebookhttp://www.facebook.com/Wizcorp
|LinkedIn http://www.linkedin.com/company/wizcorp

**Comment by chamerling** [comment]
Have a look to settings.js (https://github.com/obazoud/statusdashboard/blob/master/settings.js).

@obazoud WDYT about such feature? I planned to implemented it with storage and REST API but busy times these days...

**Comment by obazoud** [comment]
yes it will be a great feature.
but what about security ?

**Comment by chamerling** [comment]
API level security? I am currently implementing a OAuth solution in node for another project ;)

**Comment by stelcheck** [comment]
For now, i am looking at using this module as an submodule in a project.
Which mean that i am thinking of adding a code api, but not an http api.

From there, I assume it would be possible to add it though. It would also
allow plugins access to it, should that be considered relevant.

Quick note on security: I think a safe way would be through API key and
ACLs combined, considering that updates should in general come from a
specific network. But as I said, I think ill leave that aside for now :)

Kind regards,
