### ISSUE TITLE
TCP connection to services that give no response besides connected

### ISSUE THREAD

**Issue by jortizv** [statusdashboard/statusdashboard#37]
I haven't being able to figure this out. I basically want to monitor a service.. like for example RDP windows machine, or any other TCP service, then what do I put in the settings to make this work??

```
  name: 'Service', 
  label: 'service check',
  check: 'tcp',
  host: '192.168.0.1', 
  port: '3389',
  cmd: '',
  rcv: ''
```

this will eventually failed with connection refused, as there is no much documentation I cam creating this "new issue"

thanks

J

**Comment by obazoud** [comment]
I have no RDP to test.
But with Redis, demo settings is:

```
  {
      name: 'redis', 
      label: 'Redis server @ local',
      check: 'tcp',
      host: '127.0.0.1', 
      port: '6379',
      cmd: 'PING\r\n',
      rcv: '+PONG\r\n'
    }
```

And I can test with telnet:

```
 % telnet 127.0.0.1 6379
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
ping
+PONG
```

Could you test a similar telnet command ?

**Comment by jortizv** [comment]
Actually I did telnet to 3389, how ever there is no ping or any other command to get a response, just the fact that it allows the TCP connection which means is active.
would it be possible just to just to check for success of a TCP connection without waiting for a particular response?

thx

J

**Comment by chamerling** [comment]
@jortizv, you should have a look to https://github.com/obazoud/statusdashboard/blob/master/api.js#L195 and suggest a workaround.
In your case, you just need to be able to connect without sending any data and without having any timeout. It may be useful to introduce a new type of 'service check' and I think it will be easier when @obazoud will merge the last pull request.
