### ISSUE TITLE
nodemailer configuration

### ISSUE THREAD

**Issue by stelcheck** [statusdashboard/statusdashboard#48]
Quick question, can we use Sendmail instead of GMail or other mail providers? How much configuration is available here?

**Comment by obazoud** [comment]
Nodemailer documentation [says](https://github.com/andris9/Nodemailer#possible-transport-methods) that severals transport methods are available: SMTP, Amazon SES, Sendmail for utilizing systems sendmail command.

So we can add this parameters available via settings.

**Comment by obazoud** [comment]
No more feedbacks, closing issue.
