### ISSUE TITLE
User-Agent Specification

### ISSUE THREAD

**Issue by oblogic7** [statusdashboard/statusdashboard#49]
I ran into a problem where Apache was returning a 403 error for sites on a particular host.  This was only happening when requesting the page via http.get or telnet.  I narrowed it down to Apache DoS protection.  All I had to do to get around the problem is to specify a User-Agent for my request.

When I add the user agent to my settings.js file via headers: {'User-Agent': 'Mozilla/5.1...'}, the site begins returning code 200 instead of a 403.  However, the dashboard is reporting that the status is unknown for the host.  Any ideas why this would be happening just from specifying a user agent?

Edit: The host will actually show UP for a few seconds but then goes back to Unknown.  Not sure why it isn't consistent.

**Comment by obazoud** [comment]
Y have to add headers in settings.

```
{
      name: 'test', 
      label: 'test',
      check: 'http',
      host: 'my.example.com', 
      port: '80',
      path: '/',
      headers: {
      'User-Agent': 'Mozilla/5.1...'
      }
}
```

Please free to re open if you have a question.
