### ISSUE TITLE
Twitter Notifications

### ISSUE THREAD

**Issue by sreeix** [statusdashboard/statusdashboard#5]
Hi,
I  just implemented the twitter notifications for a service going down and coming back up. For me it is a simple way of sending SMS notifications to the followers of this twitter user. It is quite raw, but was if you are interested i could send a pull request.
Couple of things before i could get a clean implementation
1) each service gets only the settings for itself. This makes it hard to implement something like a global twitter application key settings for all the services to use. What are your thoughts on services having access to the global options?
2) For not spamming the users, and for better status display holding on to the last update status of a service is useful( to say that it's just gone down or come back up). Do you have any objection to holding on to last state of a service. almost akin to Hudson/cruisecontrol having last build status and current build status.

3) The failure code is sort of duplicated across the Service types, this means that i have to add a hook to every service error handler. Would it not be nice to have something like a service event emitter, that we can hook new notifications off? Almost like plugins. This way status dashboard does not need to have dependencies on twitter etc.

Let me know. i can send a pull request for all or either of them.
My fork is  here
https://github.com/sreeix/statusdashboard/tree/twitter%2Fsms_notification

**Comment by obazoud** [comment]
Hi,

A bit busy these days, usually I'm more responsive.
This will be a great to have Twitter notification.
- My road map about notification is a chrome extension
  (https://github.com/obazoud/statusdashboard-chrome) and I am also
  working on IRC bot, and may be later on RSS feed.
  With statusdashboard-chrome, a notification dialog appears only if
  something has changed. So, I would like to have a json diff inside
  statusdashboard, like:
  {"lastup": x, "up":y, ... "services": {{"service":"xxx',
  "lastState":"up", "newState:"critical"}, ...}}
- I totally agree with you, notification libs (twitter, irc, ...)
  should not be include in statusdashboard. Plugin mechanism looks
  great. Have you an example ?
- the last point: not easy to find a good way to configure notifcation
  system inside statusdashboard

So, currently, my preference is to build long polling changes
notifications. And to create statusdashboard-{twitter,irc,rss, ...}
module to consume this new REST api.

What do you think?

Olivier.

On Sat, Jun 18, 2011 at 22:37, sreeix
reply@reply.github.com
wrote:

**Comment by sreeix** [comment]
No problems with the slow response. I really like the dashboard, and had been considering implementing something similar for a long time.
- Let me implement something simple that can plugged in instead of being inlined into statusdashboard.
- I agree with the last status/new status in status dashboard. I will start to use that in my changes.
  I will send separate pull requests to you on these(feel free to disagree/reject/suggest changes) and then go from there.
  
  My use case with twitter is this.  If some of the services go down, i want to an sms to be received by folks on my team. The simple way to implement it is tweet with a team's twitter account. Which most members of the team follow, and if we set mobile notifications on twitter. it makes is really neat. no maintenance when adding/dropping team members.
  i was also thinking of building in login(to get oauth tokens) into twitter into the main page. :-)

**Comment by obazoud** [comment]
Just pushed.
