### ISSUE TITLE
Unable to deploy application locally/ on heroku

### ISSUE THREAD

**Issue by MaximeHeckel** [statusdashboard/statusdashboard#53]
I'm unable to deploy the application on my machine and even on heroku. 

Is there some configurations to do before besides of modifying the setting.js file ?

**Comment by chamerling** [comment]
What is the problem? Any logs?

**Comment by MaximeHeckel** [comment]
I just found that I needed to execute node /bin/statusdashboard to run it locally

node server.js doesn't work. 

Even stranger when I try to deploy on heroku I get the "Application Error" message, see http://fierce-river-4425.herokuapp.com/

**Comment by chamerling** [comment]
Check the heroku logs. I have a sample here on how to use the statusdashboard api to create and deploy the app on heroku https://github.com/chamerling/statusdashboard-server

**Comment by MaximeHeckel** [comment]
Thank you it works !
