### ISSUE TITLE
Twitter Username

### ISSUE THREAD

**Issue by maclover7** [statusdashboard/statusdashboard#57]
Hi, how do I add my Twitter username, to have SD send out tweets?

**Comment by obazoud** [comment]
Hi @maclover7 
- There are no twitter template, so you have to modifiy here https://github.com/obazoud/statusdashboard/blob/master/plugins/twitter/twitter_plugin.js.
- The twitter account that sends tweet is identified by settings: consumer_key, consumer_key, consumer_secret, access_token_key, access_token_secret.

**Comment by obazoud** [comment]
feel free to comment and i'll re-open.
