### ISSUE TITLE
No example is working

### ISSUE THREAD

**Issue by Sicaine** [statusdashboard/statusdashboard#61]
Hey,

there is no example working. Not your own or other linked company site.

Perhaps  you can check that out?

Tx,

Sigi

**Comment by obazoud** [comment]
hi,

what do you mean by 'not working' ? Could you send us stack trace or something to debug ?

Thanks.

**Comment by chamerling** [comment]
I think that he wants to say that your online demos are down

**Comment by Sicaine** [comment]
chamerling is right; I meant those urls in your readme.md like http://statusdashboard-node.herokuapp.com

Cya,

Sigi

**Comment by obazoud** [comment]
ok I will investigate

**Comment by obazoud** [comment]
http://statusdashboard-node.herokuapp.com/ is up.

Thanks @Sicaine.
