### ISSUE TITLE
broken in new node.js

### ISSUE THREAD

**Issue by styygeli** [statusdashboard/statusdashboard#62]
this depends on node-waf but it's deprecated in the node-0.10+

http://stackoverflow.com/questions/15024421/node-js-centos-node-waf/15979279#15979279

**Comment by obazoud** [comment]
Is it broken or deprecated ?
Could you provide us a stack trace ?

**Comment by styygeli** [comment]
It's just deprecated :) The link I posted explains the problem.

"node-waf is deprecated and was removed from node 0.10: https://github.com/joyent/node/issues/3475. You should open an issue with the package you are trying to use to get it updated to node-gyp."

**Comment by jpbriend** [comment]
Seems to be solved via the upgrade to hiredis@0.1.17.

**Comment by obazoud** [comment]
Thanks @jpbriend 
Closing this issue.
